version: 2

registries:

  github-privacyguides:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.REPO_PAT}}

updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "jonaharagon"
    reviewers:
      - "jonaharagon"
    labels:
      - "fix:github_actions"
  
  # Maintain submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    registries:
      - github-privacyguides
    schedule:
      interval: "daily"
    labels:
      - "fix:submodules"

  # Maintain dependencies for pipenv
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    registries:
      - github-privacyguides
    schedule:
      interval: "daily"
    assignees:
      - "jonaharagon"
    reviewers:
      - "jonaharagon"
    labels:
      - "fix:python"
