[build]
    publish = "site/"
    command = "mkdocs build --config-file config/mkdocs.en.yml && mkdocs build --config-file config/mkdocs.he.yml && mkdocs build --config-file config/mkdocs.fr.yml && mkdocs build --config-file config/mkdocs.nl.yml && mv _redirects site/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'none'; script-src https://www.privacyguides.org https://api.privacyguides.net 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src data: 'self'; connect-src https://api.github.com https://*.privacyguides.net 'self'; frame-src https://*.privacyguides.net; frame-ancestors 'none'"

[[headers]]
  for = "/about/donate/"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; script-src https://opencollective.com https://www.privacyguides.org https://api.privacyguides.net 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src https://opencollective.com data: 'self'; connect-src https://api.github.com https://api.privacyguides.net 'self'; frame-src https://opencollective.com; frame-ancestors 'none'"

[[redirects]]
    from = "/.well-known/matrix/*"
    to = "https://matrix.privacyguides.org/.well-known/matrix/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/kb"
    to = "/en/basics/threat-modeling/"

[[redirects]]
    from = "/:lang/kb"
    to = "/:lang/basics/threat-modeling/"

[[redirects]]
    from = "/coc"
    to = "/en/CODE_OF_CONDUCT/"

[[redirects]]
    from = "/team"
    to = "/en/about/"

[[redirects]]
    from = "/browsers"
    to = "/en/desktop-browsers/"

[[redirects]]
    from = "/blog"
    to = "https://blog.privacyguides.org"

[[redirects]]
    from = "/blog/2021/12/01/firefox-privacy-2021-update"
    to = "https://blog.privacyguides.org/2021/12/01/firefox-privacy-2021-update/"

[[redirects]]
    from = "/blog/2021/09/14/welcome-to-privacy-guides"
    to = "https://blog.privacyguides.org/2021/09/14/welcome-to-privacy-guides/"

[[redirects]]
    from = "/blog/2022/06/09/hide-nothing"
    to = "https://blog.privacyguides.org/2022/06/09/hide-nothing/"

[[redirects]]
    from = "/blog/2022/04/04/move-fast-and-break-things"
    to = "https://blog.privacyguides.org/2022/04/04/move-fast-and-break-things/"

[[redirects]]
    from = "/blog/2021/11/01/virtual-insanity"
    to = "https://blog.privacyguides.org/2021/11/01/virtual-insanity"

[[redirects]]
    from = "/basics/dns-overview"
    to = "/en/advanced/dns-overview/"

[[redirects]]
    from = "/basics/tor-overview"
    to = "/en/advanced/tor-overview/"

[[redirects]]
    from = "/real-time-communication/communication-network-types"
    to = "/en/advanced/communication-network-types"

[[redirects]]
    from = "/advanced/real-time-communication"
    to = "/en/advanced/communication-network-types"

[[redirects]]
    from = "/android/overview"
    to = "/en/os/android-overview/"

[[redirects]]
    from = "/linux-desktop/overview"
    to = "/en/os/linux-overview/"

[[redirects]]
    from = "/android/grapheneos-vs-calyxos"
    to = "https://blog.privacyguides.org/2022/04/21/grapheneos-or-calyxos/"

[[redirects]]
    from = "/ios/configuration"
    to = "https://blog.privacyguides.org/2022/10/22/ios-configuration-guide/"

[[redirects]]
    from = "/linux-desktop/hardening"
    to = "https://blog.privacyguides.org/2022/04/22/linux-system-hardening/"

[[redirects]]
    from = "/linux-desktop/sandboxing"
    to = "https://blog.privacyguides.org/2022/04/22/linux-application-sandboxing/"

[[redirects]]
    from = "/advanced/signal-configuration-hardening"
    to = "https://blog.privacyguides.org/2022/07/07/signal-configuration-and-hardening/"

[[redirects]]
    from = "/real-time-communication/signal-configuration-hardening"
    to = "https://blog.privacyguides.org/2022/07/07/signal-configuration-and-hardening/"

[[redirects]]
    from = "/advanced/integrating-metadata-removal"
    to = "https://blog.privacyguides.org/2022/04/09/integrating-metadata-removal/"

[[redirects]]
    from = "/advanced/erasing-data"
    to = "https://blog.privacyguides.org/2022/05/25/secure-data-erasure/"

[[redirects]]
    from = "/providers/dns"
    to = "/en/dns/"

[[redirects]]
    from = "/software/video-streaming"
    to = "/en/video-streaming/"

[[redirects]]
    from = "/providers/vpn"
    to = "/en/vpn/"

[[redirects]]
    from = "/operating-systems"
    to = "/en/desktop/"

[[redirects]]
    from = "/providers/email"
    to = "/en/email/"

[[redirects]]
    from = "/threat-modeling"
    to = "/en/basics/threat-modeling/"

[[redirects]]
    from = "/software/passwords"
    to = "/en/passwords/"

[[redirects]]
    from = "/self-contained-networks"
    to = "/en/tor/"

[[redirects]]
    from = "/privacy-policy"
    to = "/en/about/privacy-policy/"

[[redirects]]
    from = "/metadata-removal-tools"
    to = "/en/data-redaction/"

[[redirects]]
    from = "/basics"
    to = "/en/kb"

[[redirects]]
    from = "/software/file-encryption"
    to = "/en/encryption/"

[[redirects]]
    from = "/providers"
    to = "/en/tools/#service-providers"

[[redirects]]
    from = "/software/notebooks"
    to = "/en/notebooks/"

[[redirects]]
    from = "/software/calendar-contacts"
    to = "/en/calendar/"

[[redirects]]
    from = "/calendar-contacts"
    to = "/en/calendar/"

[[redirects]]
    from = "/software/metadata-removal-tools"
    to = "/en/data-redaction/"

[[redirects]]
    from = "/contact"
    to = "/en/about/"

[[redirects]]
    from = "/welcome-to-privacy-guides"
    to = "https://blog.privacyguides.org/2021/09/14/welcome-to-privacy-guides/"

[[redirects]]
    from = "/software/email"
    to = "/en/email-clients/"

[[redirects]]
    from = "/providers/paste"
    to = "/en/tools/"

[[redirects]]
    from = "/providers/search-engines"
    to = "/en/search-engines/"

[[redirects]]
    from = "/software/productivity"
    to = "/en/productivity/"

[[redirects]]
    from = "/software/real-time-communication"
    to = "/en/real-time-communication/"

[[redirects]]
    from = "/blog/2019/10/05/understanding-vpns"
    to = "https://www.jonaharagon.com/posts/understanding-vpns/"

[[redirects]]
    from = "/terms-and-notices"
    to = "/en/about/notices/"

[[redirects]]
    from = "/software/file-sharing"
    to = "/en/file-sharing/"

[[redirects]]
    from = "/software/networks"
    to = "/en/tor/"

[[redirects]]
    from = "/social-news-aggregator"
    to = "/en/news-aggregators/"

[[redirects]]
    from = "/basics/erasing-data"
    to = "https://blog.privacyguides.org/2022/05/25/secure-data-erasure/"

[[redirects]]
    from = "/linux-desktop"
    to = "/en/desktop/"

[[redirects]]
    from = "/assets/*"
    to = "/en/assets/:splat"

[[redirects]]
    from = "/fr/*"
    to = "/fr/404/index.html"
    status = 404

[[redirects]]
    from = "/he/*"
    to = "/he/404/index.html"
    status = 404

[[redirects]]
    from = "/nl/*"
    to = "/nl/404/index.html"
    status = 404

[[redirects]]
    from = "/*"
    to = "/en/404/index.html"
    status = 404
